name: multimodal-covid
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip=22.3.1
  
  # Core ML frameworks
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pytorch-cuda=11.6
  - tensorflow=2.12.0
  
  # Scientific computing
  - numpy=1.24.1
  - pandas=1.5.2
  - scipy=1.10.0
  - scikit-learn=1.2.0
  
  # Audio processing
  - librosa=0.9.2
  - soundfile=0.11.0
  - ffmpeg=5.1.2
  
  # Visualization
  - matplotlib=3.6.2
  - seaborn=0.12.2
  
  # Data handling
  - h5py=3.8.0
  - pillow=9.4.0
  
  # Development tools
  - jupyter=1.0.0
  - ipykernel=6.20.2
  - black=22.12.0
  - pytest=7.2.0
  
  # System utilities
  - psutil=5.9.4
  
  # pip dependencies (not available in conda)
  - pip:
    - transformers==4.25.1
    - xgboost==1.7.3
    - imbalanced-learn==0.10.1
    - plotly==5.12.0
    - tqdm==4.64.1
    - click==8.1.3
    - fastapi==0.88.0
    - uvicorn==0.20.0
    - pyyaml==6.0
    - python-dotenv==0.21.0
    - wandb==0.13.7
    - tensorboard==2.12.0
    - memory-profiler==0.60.0
    - pytest-cov==4.0.0
    - flake8==6.0.0
    - isort==5.12.0

---
